sudo:required
service:
    - docker
before_install:
    - docker build -t nahid0002/docker-react-project -f Dockerfile.dev
script:
    - docker run nahid0002/docker-react-project npm run test -- --coverage
deploy:
    provider: elesticbeanstalk
    region: "us-west-1"
    app: "docker-react" 
    env: "docker-react-env" 
    bucket_name: "elasticbeanstalk-us-east-1-652169129391"
    bucket_paath: "docker-react"  
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_ACCESS_KEY"