sudo:required
service:
    - docker
before_install:
    - docker build -t nahid0002/docker-react-project -f Dockerfile.dev
script:
    - docker run nahid0002/docker-react-project npm run test -- --coverage